### ISSUE TITLE
Add `init` command.

### ISSUE THREAD

**Issue by rumbleFTW** [rumbleFTW/packet#1]
This new command will work like cargo's `init` command, and will setup a new Project in an existing directory.

This can be implemented in two steps:
1. Add the behavior in `src/commands.init.rs` file.
2. Create a new CLI subcommand in the `src/main.rs` file.

Reference: https://doc.rust-lang.org/cargo/commands/cargo-init.html.
PS: We are currently focusing on the base command, so it should just be able to set-up a new project in the directory by creating the necessary files and env.

**Comment by gSayak** [comment]
Issue is Fixed in #2 

Added the `init` command to initialize and setup a new project in the Existing directory
